apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: example
  namespace: default
spec:
  rules:
    authorization:
      SOMETHING:
        opa:
          externalPolicy:
            sharedSecretRef:
              key: some-key
              name: some-name
  targetRef:
    group: some-group
    kind: SomeKind
    name: some-name
