apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-kuadrant-operator
  namespace: operators
spec:
  channel: stable
  name: kuadrant-operator
  source: operatorhubio-catalog
  sourceNamespace: olm